Allow to use a refresh token in the provider to get the access token
prismatic-io/terraform-provider-prismatic pull request #4
Opened 2024-11-12 16:23 UTC by fetilla

2025-02-12 22:23 UTC, ryanwersal requested changes
Thank you for the contribution! 

I left a handful of comments though most are to drive towards deprecating and eventually removing the original access token authentication in favor of this refresh token behavior. 

I think the provider attributes are worth the update but there's no need to go through the other error text as that can be sorted out later when the `token` attribute is fully removed.

2025-02-12 22:23 UTC, ryanwersal commented on internal/provider/provider.go
> +					Description: "A [refresh token to use for headless authentication](https://prismatic.io/docs/cli/cli-usage/#headless-prism-usage-for-cicd-pipelines), of Prismatic API calls. Token parameter is n
I definitely agree with adding refresh token support and I think we should take it a step further. Both provider attributes link to the [headless `prism` CLI docs](https://prismatic.io/docs/cli/bash-scripting/#headless-prism-usage-for-cicd-pipelines) which notably advise using a refresh token exclusively and I think we should align with that by [formally deprecating the `token` attribute](https://developer.hashicorp.com/terraform/plugin/framework/deprecations#provider-attribute-removal). 

Something along the lines of the following should do for the `DeprecationMessage`:

> Access token use has been deprecated in favor of using refresh tokens. Please migrate provider configuration to use the new `refresh_token` attribute instead.

Then removing the token and refresh token interplay from `refresh_token`'s description text, perhaps:

> A [refresh token to use for headless authentication](https://prismatic.io/docs/cli/cli-usage/#headless-prism-usage-for-cicd-pipelines) to the Prismatic API.

2025-02-12 22:23 UTC, ryanwersal commented on templates/index.md.tmpl
Really appreciate the docs update! If these could be adjusted to present `refresh_token` as the go-forward means of authenticating the provider instead of the existing `token` flow, that would be perfect.

2025-02-12 22:23 UTC, ryanwersal commented on go.sum
What caused the addition of these lines to the lockfile?

2025-02-13 16:43 UTC, fetilla commented on go.sum
Sorry about that, removing. No idea why I got that, I believed it was part of the `make init`.

2025-02-13 16:47 UTC, fetilla commented on internal/provider/provider.go
> +					Description: "A [refresh token to use for headless authentication](https://prismatic.io/docs/cli/cli-usage/#headless-prism-usage-for-cicd-pipelines), of Prismatic API calls. Token parameter is n
Perfect then, I updated the documentation. I just was afraid to change the token parameter, but of course I agree with you, it would be better deprecating it than maintaining it.

2025-02-13 17:00 UTC, fetilla commented on templates/index.md.tmpl
I updated the documentation deprecating the `token` in favor of `refresh_token`.

2025-02-24 10:12 UTC, fetilla commented
I resolved the issues, please let me know if you have more comments in the review. Thanks in advance.

2025-02-24 16:26 UTC, ryanwersal requested changes
Docs updates look really good, thanks for doing that! Just one comment to ensure we're following Terraform's guidance on deprecating provider attributes and we should be set.

2025-02-24 16:26 UTC, ryanwersal commented on internal/provider/provider.go
> +					Description: "Access token use has been deprecated in favor of using refresh tokens. Please migrate provider configuration to use the new refresh_token attribute instead.",
I think this text should be provided to the [`DeprecationMessage` property](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/schemas#deprecationmessage) instead of the `Description` (which can likely stay the same as previous) per [Terraform's provider attribute removal docs](https://developer.hashicorp.com/terraform/plugin/framework/deprecations#provider-attribute-removal).

2025-03-04 11:57 UTC, fetilla commented on internal/provider/provider.go
> +					Description: "Access token use has been deprecated in favor of using refresh tokens. Please migrate provider configuration to use the new refresh_token attribute instead.",
Remember it is the schema provider, is not a Resource or Data source where `DeprecateionMessage` can be applied. But I found [Deprecated](https://github.com/hashicorp/terraform-plugin-sdk/blob/5dfe31a49ac8e5fe0fd2feef9c7bab81b4e66dfb/helper/schema/schema.go#L341) property for provider schema. I am going to restore the previous descpription and indicate in that property why is deprecated.

2025-03-04 12:08 UTC, fetilla commented on internal/provider/provider.go
> +					Description: "Access token use has been deprecated in favor of using refresh tokens. Please migrate provider configuration to use the new refresh_token attribute instead.",
In fact I impoved a bit the links to match with real pages in your current documentation.

2025-03-06 19:18 UTC, ryanwersal approved these changes
Looks great! Thank you!

There's some test failures and some issue with generating documentation but I'll get this landed, sort that out, and get a release shipped.

2025-03-06 19:19 UTC, merged

2025-03-06 20:16 UTC, ryanwersal commented
This has been released as v0.2.0 and is now [available on the Terraform registry](https://registry.terraform.io/providers/prismatic-io/prismatic/latest/docs). Thanks again!